# Generated by Django 2.2.6 on 2019-11-13 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191113_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_verifyied',
            new_name='email_verified',
        ),
    ]
