# Generated by Django 2.2.6 on 2019-11-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth',
            field=models.CharField(choices=[('Email', 'Email'), ('Github', 'Github'), ('Kakao', 'Kakao')], default='Email', max_length=40),
        ),
    ]
