# Generated by Django 2.2.6 on 2019-11-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20191105_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='photo_list',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='rooms.Photo'),
        ),
    ]
