# Generated by Django 2.2.6 on 2019-11-16 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_photo_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='photo_list',
        ),
    ]
